/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as CompetitorsIndexRouteImport } from './routes/competitors/index'
import { Route as CompetitorsCompetitorIdRouteImport } from './routes/competitors/$competitorId'
import { Route as CompetitorsNewRouteImport } from './routes/competitors/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsIndexRoute = CompetitorsIndexRouteImport.update({
  id: '/competitors/',
  path: '/competitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsCompetitorIdRoute = CompetitorsCompetitorIdRouteImport.update({
  id: '/competitors/$competitorId',
  path: '/competitors/$competitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsNewRoute = CompetitorsNewRouteImport.update({
  id: '/competitors/new',
  path: '/competitors/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/competitors/$competitorId': typeof CompetitorsCompetitorIdRoute
  '/competitors/new': typeof CompetitorsNewRoute
  '/competitors/': typeof CompetitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/competitors/$competitorId': typeof CompetitorsCompetitorIdRoute
  '/competitors/new': typeof CompetitorsNewRoute
  '/competitors': typeof CompetitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/competitors/$competitorId': typeof CompetitorsCompetitorIdRoute
  '/competitors/new': typeof CompetitorsNewRoute
  '/competitors/': typeof CompetitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/competitors/$competitorId'
    | '/competitors/new'
    | '/competitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/competitors/$competitorId'
    | '/competitors/new'
    | '/competitors'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/competitors/$competitorId'
    | '/competitors/new'
    | '/competitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CompetitorsCompetitorIdRoute: typeof CompetitorsCompetitorIdRoute
  CompetitorsNewRoute: typeof CompetitorsNewRoute
  CompetitorsIndexRoute: typeof CompetitorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/': {
      id: '/competitors/'
      path: '/competitors'
      fullPath: '/competitors/'
      preLoaderRoute: typeof CompetitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/$competitorId': {
      id: '/competitors/$competitorId'
      path: '/competitors/$competitorId'
      fullPath: '/competitors/$competitorId'
      preLoaderRoute: typeof CompetitorsCompetitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/new': {
      id: '/competitors/new'
      path: '/competitors/new'
      fullPath: '/competitors/new'
      preLoaderRoute: typeof CompetitorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CompetitorsCompetitorIdRoute: CompetitorsCompetitorIdRoute,
  CompetitorsNewRoute: CompetitorsNewRoute,
  CompetitorsIndexRoute: CompetitorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
